/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;
import Gestión.Caja;
import Entities.Producto;
import Entities.Aseo;
import Entities.Bebida;
import Entities.Enlatado;
import Entities.EnumTipoProd;
import Entities.Granos;
import Entities.Mecato;
import Gestión.Inventario;
import java.time.LocalDate;
import java.time.Year;
import java.util.ArrayList;
import java.util.Map;
import javax.swing.DefaultComboBoxModel;

public class CreacionProducto extends javax.swing.JFrame {
    private Main parent;
    private Caja caja;

    public Main getParent() {
        return parent;
    }

    public void setParent(Main parent) {
        this.parent = parent;
    }
    public CreacionProducto(Main parent, Caja caja, Inventario inventario){
        this.caja = caja;
        this.parent = parent;
        this.parent.getCaja().setInventario(inventario);
        initComponents();
        inicializarComboTipoProd();
    }
        private void inicializarComboTipoProd() {
    txtTipoProd.setModel(new DefaultComboBoxModel<>(new String[]{
        "Bebida", "Mecato", "Aseo", "Enlatado", "Grano"
    }));
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        lblPrecioMayor = new javax.swing.JLabel();
        txtPrecioMayor = new javax.swing.JTextField();
        lblPrecioMenor = new javax.swing.JLabel();
        txtPrecioMenor = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtTipoProd = new javax.swing.JComboBox<>();
        btnGuardar = new javax.swing.JToggleButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtErrorRegistro = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        txtDay = new javax.swing.JTextField();
        txtMonth = new javax.swing.JTextField();
        txtYear = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtEtiquetas = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblID.setText("ID : ");

        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre : ");

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        jLabel2.setText("Cantidad :");

        lblPrecioMayor.setText("Precio Mayor :");

        lblPrecioMenor.setText("Precio Menor :");

        jLabel5.setText("Tipo Producto :");

        txtTipoProd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aseo", "Bebida", "Mecato", "Granos", "Enlatado" }));
        txtTipoProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTipoProdActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane4.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane4.setAutoscrolls(true);

        txtErrorRegistro.setColumns(20);
        txtErrorRegistro.setRows(5);
        jScrollPane4.setViewportView(txtErrorRegistro);

        jLabel3.setText("Fecha de Vencimiento : ");

        txtDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDayActionPerformed(evt);
            }
        });

        txtMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMonthActionPerformed(evt);
            }
        });

        jLabel6.setText("DD");

        jLabel7.setText("MM");

        jLabel8.setText("YYYY");

        txtEtiquetas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEtiquetasActionPerformed(evt);
            }
        });

        jLabel9.setText("Etiqueta :");

        jLabel10.setText("#Escriba asi: etiqueta1,etiqueta2,...,etiquetak");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPrecioMayor, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(lblID, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPrecioMenor, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPrecioMenor, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPrecioMayor, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTipoProd, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtDay, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(27, 27, 27)
                                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGuardar))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(104, 104, 104)
                                .addComponent(txtEtiquetas, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 9, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblID)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrecioMayor)
                    .addComponent(txtPrecioMayor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrecioMenor)
                    .addComponent(txtPrecioMenor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtTipoProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txtEtiquetas, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(btnGuardar))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtTipoProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTipoProdActionPerformed
        
    }//GEN-LAST:event_txtTipoProdActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        Map<Long, Double> cantidades = parent.getCaja().getInventario().getCantidades(); //Atajo
        
        try {
            String nombre = txtNombre.getText().trim();
            String id = txtID.getText().trim();
            String Cantidad  = txtCantidad.getText().trim();
            String PrecioMayor = txtPrecioMayor.getText().trim();
            String PrecioMenor = txtPrecioMenor.getText().trim();
            String tipoSeleccionado = (String) txtTipoProd.getSelectedItem();
            String dia = txtDay.getText().trim();
            String mes = txtMonth.getText().trim();
            String annio = txtYear.getText().trim();
            String textoEtiquetas = txtEtiquetas.getText().trim();
        if (nombre.isBlank() || id.isBlank() || Cantidad.isBlank() ||
        PrecioMayor.isBlank() || PrecioMenor.isBlank() || tipoSeleccionado == null || 
                dia.isBlank() || mes.isBlank() || annio.isBlank()) {
        throw new IllegalArgumentException("Todos los campos son obligatorios.");
        }
        if (!nombre.matches("[a-zA-ZáéíóúÁÉÍÓÚñÑ0-9\\s]+")) {
            throw new IllegalArgumentException("El nombre solo puede contener letras y espacios.");
        }

        if (!id.matches("\\d+")) {
            throw new IllegalArgumentException("El ID solo debe contener números.");
        }

        // Validar que Cantidad solo contenga números (y opcionalmente punto decimal)
        if (!Cantidad.matches("\\d+(\\.\\d+)?")) {
            throw new IllegalArgumentException("La cantidad debe ser un número válido.");
        }

        // Validar que Precio Mayor solo contenga números (y opcionalmente punto decimal)
        if (!PrecioMayor.matches("\\d+(\\.\\d+)?")) {
            throw new IllegalArgumentException("El precio mayor debe ser un número válido.");
        }

        // Validar que Precio Menor solo contenga números (y opcionalmente punto decimal)
        if (!PrecioMenor.matches("\\d+(\\.\\d+)?")) {
            throw new IllegalArgumentException("El precio menor debe ser un número válido.");
        }
        if (!dia.matches("\\d+")){
            throw new IllegalArgumentException("El día solo debe contener números.");
        }
        if (!mes.matches("\\d+")){
            throw new IllegalArgumentException("El mes solo debe contener números.");
        }
        if (!annio.matches("\\d+")){
            throw new IllegalArgumentException("El año solo debe contener números.");
        }
        if (!textoEtiquetas.isBlank() && !textoEtiquetas.matches("[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s,]*")) {
            throw new IllegalArgumentException("Las etiquetas solo puede contener letras y espacios.");
        }
        
        long Id = Long.parseLong(id);
        double cantidad = Double.parseDouble(Cantidad);
        double preciomenor = Double.parseDouble(PrecioMenor);
        double preciomayor = Double.parseDouble(PrecioMayor);
        EnumTipoProd tiposeleccionado = EnumTipoProd.ASEO;
        int Dia = Integer.parseInt(dia);
        int Mes = Integer.parseInt(mes);
        int Annio = Integer.parseInt(annio);
        LocalDate fechaVencimiento = LocalDate.of(Annio, Mes, Dia);
        ArrayList<String> etiquetas = new ArrayList<>();
        String[] etiquetasArray = textoEtiquetas.split(",");
        for (String etiqueta : etiquetasArray) {
            etiquetas.add(etiqueta.trim());
    }
        if (preciomenor<preciomayor){
            throw new IllegalArgumentException("El precio por mayor debe ser menor o igual al precio por menor.");
        }
        
        if (Annio < Year.now().getValue()){
            throw new IllegalArgumentException("La fecha de vencimiento es incorrecta.");
        }
        switch(tipoSeleccionado){
            case "Aseo":
               Aseo aseo = new Aseo (nombre, Id, cantidad, preciomenor, preciomayor, fechaVencimiento, etiquetas);
               parent.getCaja().getInventario().crearProductos(aseo);
               cantidades.put(Id, cantidad);
            case "Bebida":
               Bebida bebida = new Bebida (nombre, Id, cantidad, preciomenor, preciomayor, fechaVencimiento, etiquetas);
               parent.getCaja().getInventario().crearProductos(bebida);
               cantidades.put(Id, cantidad);
            case "Mecato":
               Mecato mecato = new Mecato (nombre, Id, cantidad, preciomenor, preciomayor, fechaVencimiento, etiquetas);
               parent.getCaja().getInventario().crearProductos(mecato);
               cantidades.put(Id, cantidad);
            case "Enlatado":
                Enlatado enlatado = new Enlatado (nombre, Id, cantidad, preciomenor, preciomayor, fechaVencimiento, etiquetas);
                parent.getCaja().getInventario().crearProductos(enlatado);
                cantidades.put(Id, cantidad);
            case "Grano":
               Granos granos = new Granos (nombre, Id, cantidad, preciomenor, preciomayor, fechaVencimiento, etiquetas);
               parent.getCaja().getInventario().crearProductos(granos);
               cantidades.put(Id, cantidad);
        }
        
        /*System.out.println("Producto creado correctamente.");
        for (Producto p : parent.getCaja().getInventario().getProductos()) {
            p.imprimirFicha();
    }
        for (Long idProd: cantidades.keySet()){
            Double cantidadProd = cantidades.get(idProd);
            System.out.println("ID Producto: " + idProd + ", Cantidad: " + cantidadProd);
        }*/
        
        this.dispose();
        InventarioSistema inventarioSistema = new InventarioSistema(parent);
        inventarioSistema.setVisible(true);

    } catch (IllegalArgumentException ex) {
        txtErrorRegistro.setText(ex.getMessage());
    } catch (Exception ex) {
        txtErrorRegistro.setText("Error inesperado: " + ex.getMessage());
}
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDayActionPerformed

    private void txtMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMonthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMonthActionPerformed

    private void txtEtiquetasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEtiquetasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEtiquetasActionPerformed

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblPrecioMayor;
    private javax.swing.JLabel lblPrecioMenor;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtDay;
    private javax.swing.JTextArea txtErrorRegistro;
    private javax.swing.JTextField txtEtiquetas;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtMonth;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecioMayor;
    private javax.swing.JTextField txtPrecioMenor;
    private javax.swing.JComboBox<String> txtTipoProd;
    private javax.swing.JTextField txtYear;
    // End of variables declaration//GEN-END:variables
}
