

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import Entities.utilJtextField;
import java.time.LocalDate;
import javax.swing.text.AbstractDocument;
import Gestión.Venta;
import UI.Main;
import java.time.LocalDateTime;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */

public class Devolucion extends javax.swing.JFrame {

    /**
     * Creates new form Devoluciones
     */
    private Main parent;
    public Devolucion(Main parent) {
        this.parent = parent;
        initComponents();
    }
    public void llenarTablaVentas(ArrayList<Venta> ventas){
    DefaultTableModel modelo =(DefaultTableModel)tableVentasDelDia.getModel();
    modelo.setRowCount(0);
    for (Venta v : ventas){
        modelo.addRow(new Object[]
        {v.getFecha(), 
        v.getTotalBruto(),
        v.getTotalVenta()});
      
    }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPedirFecha = new javax.swing.JLabel();
        lblFormatoFecha = new javax.swing.JLabel();
        txtFechaVenta = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        scrollListaVentasDia = new javax.swing.JScrollPane();
        tableVentasDelDia = new javax.swing.JTable();
        lblNoVentasEncontradas = new javax.swing.JLabel();
        btnDevolver = new javax.swing.JButton();
        lblPresioneVenta = new javax.swing.JLabel();
        lblSeleccionarVenta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblPedirFecha.setText("Ingrese la fecha en la que se realizo la venta");

        lblFormatoFecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFormatoFecha.setText("en formato AAAA-MM-DD");

        ((AbstractDocument) txtFechaVenta.getDocument()).setDocumentFilter(new utilJtextField(10));
        txtFechaVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaVentaActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        scrollListaVentasDia.setVisible(false);

        tableVentasDelDia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableVentasDelDia.setEnabled(false);
        scrollListaVentasDia.setViewportView(tableVentasDelDia);

        lblNoVentasEncontradas.setVisible(false);
        lblNoVentasEncontradas.setText("No se encontraron ventas en el día indicado.");
        lblNoVentasEncontradas.setName(""); // NOI18N

        btnDevolver.setBackground(new java.awt.Color(225, 10, 0));
        btnDevolver.setText("Hacer devolución");
        btnDevolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDevolverActionPerformed(evt);
            }
        });

        lblPresioneVenta.setVisible(false);
        lblPresioneVenta.setText("Presione la venta que quiera devolver y luego presione \"Hacer devolución\".");
        lblPresioneVenta.setName(""); // NOI18N

        lblSeleccionarVenta.setVisible(false);
        lblSeleccionarVenta.setText("No se encontraron ventas en el día indicado.");
        lblSeleccionarVenta.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        lblSeleccionarVenta.setName(""); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(lblPresioneVenta)
                .addGap(25, 25, 25))
            .addGroup(layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnBuscar)
                            .addGap(75, 75, 75))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtFechaVenta)
                            .addComponent(lblFormatoFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblPedirFecha, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addComponent(lblNoVentasEncontradas))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(scrollListaVentasDia, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(lblSeleccionarVenta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDevolver)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lblPedirFecha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFormatoFecha)
                .addGap(18, 18, 18)
                .addComponent(txtFechaVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBuscar)
                .addGap(18, 18, 18)
                .addComponent(lblNoVentasEncontradas, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPresioneVenta)
                .addGap(9, 9, 9)
                .addComponent(scrollListaVentasDia, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDevolver, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSeleccionarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFechaVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaVentaActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String fechaString;
        ArrayList<Venta> ventasDelDia = null;
        
        fechaString = txtFechaVenta.getText().trim();
        LocalDateTime fechaVenta = LocalDateTime.parse(fechaString);
        for (Venta v : parent.getCaja().getVentas()) {
            if (v.getFecha().equals(fechaVenta)) {
                ventasDelDia.add(v);

            }
        
        }
        if (ventasDelDia == null)
        {
            this.lblNoVentasEncontradas.setVisible(true);
        }
        else{
        this.llenarTablaVentas(ventasDelDia);
        this.tableVentasDelDia.setVisible(true);
        this.lblPresioneVenta.setVisible(true);
        }
        

    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnDevolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDevolverActionPerformed
    int ventaSeleccionada = this.tableVentasDelDia.getSelectedRow();
    if (ventaSeleccionada == -1){
        
    }
    
    }//GEN-LAST:event_btnDevolverActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnDevolver;
    private javax.swing.JLabel lblFormatoFecha;
    private javax.swing.JLabel lblNoVentasEncontradas;
    private javax.swing.JLabel lblPedirFecha;
    private javax.swing.JLabel lblPresioneVenta;
    private javax.swing.JLabel lblSeleccionarVenta;
    private javax.swing.JScrollPane scrollListaVentasDia;
    private javax.swing.JTable tableVentasDelDia;
    private javax.swing.JTextField txtFechaVenta;
    // End of variables declaration//GEN-END:variables
}
